package main

import (
	"log"

	"unisun/api/strapi-information-gateway/src"
	"unisun/api/strapi-information-gateway/src/config"

	"github.com/spf13/viper"
	// docs is generated by Swag CLI, you have to import it.
)

var ENV_PORT = "app.port"

func main() {
	envService := config.New("app", "./src/resource")
	if err := envService.ConfigENV(); err != nil {
		log.Panic(err)
	}

	r := src.App()
	port := viper.GetString(ENV_PORT)
	if port == "" {
		r.Run(":8080")
	} else {
		r.Run(":" + port)
	}
}
