package main

import (
	"os"

	"unisun/api/strapi-information-gateway/src"
	"unisun/api/strapi-information-gateway/src/config"
	"unisun/api/strapi-information-gateway/src/constants"
	// docs is generated by Swag CLI, you have to import it.
)

func main() {
	if os.Getenv(constants.NODE) != "production" {
		config.ConfigENV()
	}
	r := src.App()
	port := os.Getenv(constants.PORT)
	if port == "" {
		r.Run(":8080")
	} else {
		r.Run(":" + port)
	}
}
