definitions:
  model.Response:
    properties:
      error:
        type: string
      payload:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
  license: {}
paths:
  /healthcheck:
    get:
      description: Health checking for the service
      operationId: HealthCheckHandler
      produces:
      - text/plain
      summary: Health Check
  /strapi:
    post:
      description: Strapi Information Gateway for the service
      operationId: StrapiInformationGatewayHandler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: FAIL
          schema:
            $ref: '#/definitions/model.Response'
      summary: Strapi Information Gateway
swagger: "2.0"
